export const AUTH = {
    START: 'AUTH_START',
    SUCCESS: 'AUTH_SUCCESS',
    FAIL: 'AUTH_FAIL'
};

export const UI = {
    SHOW_LOADING: 'SHOW_LOADING',
    HIDE_LOADING: 'HIDE_LOADING'
};

export const ARTIST = {
    SEARCH_START: 'SEARCH_START',
    SEARCH_SUCCESS: 'ARTIST_SEARCH_SUCCESS',
    SEARCH_FAIL: 'ARTIST_SEARCH_FAIL'
};

export const I18N = {
    CHANGE_LANG: 'CHANGE_LANG'
};