export const AUTH = {
    START: 'AUTH_START',
    SUCCESS: 'AUTH_SUCCESS',
    FAIL: 'AUTH_FAIL'
};

export const UI = {
    SHOW_LOADING: 'SHOW_LOADING',
    HIDE_LOADING: 'HIDE_LOADING'
};

export const ARTIST = {
    SEARCH_START: 'SEARCH_START',
    SEARCH_SUCCESS: 'ARTIST_SEARCH_SUCCESS',
    SEARCH_FAIL: 'ARTIST_SEARCH_FAIL'
};

export const I18N = {
    CHANGE_LANG: 'CHANGE_LANG'
};

export const NOTIFICATION = {
    FETCH_SUCCESS: 'FETCH_SUCCESS',
    FETCH_FAIL: 'FETCH_FAIL'
};

export const USER_ACTION_DIALOG = {
    OPEN_LOGIN_DIALOG: 'OPEN_LOGIN_DIALOG',
    OPEN_REGISTER_DIALOG: 'OPEN_REGISTER_DIALOG',
    OPEN_CREATE_BOOKING_DIALOG: 'OPEN_CREATE_BOOKING_DIALOG',
    OPEN_BOOKING_DIALOG: 'OPEN_BOOKING_DIALOG',
    OPEN_APPOINTMENT_DIALOG: 'OPEN_APPOINTMENT_DIALOG',
    CLOSE_USER_ACTION_DIALOG: 'CLOSE_USER_ACTION_DIALOG'
};

export const SNACKBAR = {
    SHOW_SNACKBAR: 'SHOW_SNACKBAR',
    HIDE_SNACKBAR: 'HIDE_SNACKBAR'
};

export const BROWSER_NOTIFICATION = {
    SHOW_BROWSER_NOTIFICATION: 'SHOW_BROWSER_NOTIFICATION',
    RESET_BROWSER_NOTIFICATION: 'HIDE_BROWSER_NOTIFICATION'
}